headersOrigin = "config"
plugins = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/sqin/Documents/website/academic-website/public"
publishOrigin = "config"
commandOrigin = "config"
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[build.environment]
HUGO_VERSION = "0.78.0"
HUGO_ENABLEGITINFO = "true"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "*.webmanifest"

[headers.values]
Content-Type = "application/manifest+json; charset=UTF-8"

[[headers]]
for = "index.xml"

[headers.values]
Content-Type = "application/rss+xml"